### ISSUE TITLE
java.lang.NullPointerException in MainActivity 

### ISSUE THREAD

**Issue by ITanCh** [ligi/SCR#2]
```
// CRASH: org.ligi.scr (pid 17611)
// Short Msg: java.lang.NullPointerException
// Long Msg: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.v7.widget.OrientationHelper.getStartAfterPadding()' on a null object reference
// Build Label: Android/aosp_flo/flo:6.0.1/MOB30P/tianchi10041651:userdebug/test-keys
// Build Changelist: eng.tianchi.20161004.165046
// Build Time: 1475571199000
// java.lang.RuntimeException: Unable to pause activity {org.ligi.scr/org.ligi.scr.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.v7.widget.OrientationHelper.getStartAfterPadding()' on a null object reference
//  at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3381)
//  at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3340)
//  at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3315)
//  at android.app.ActivityThread.-wrap13(ActivityThread.java)
//  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1362)
//  at android.os.Handler.dispatchMessage(Handler.java:102)
//  at android.os.Looper.loop(Looper.java:148)
//  at android.app.ActivityThread.main(ActivityThread.java:5417)
//  at java.lang.reflect.Method.invoke(Native Method)
//  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
//  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
//  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
// Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.support.v7.widget.OrientationHelper.getStartAfterPadding()' on a null object reference
//  at android.support.v7.widget.StaggeredGridLayoutManager$Span.findOneVisibleChild(StaggeredGridLayoutManager.java:2345)
//  at android.support.v7.widget.StaggeredGridLayoutManager$Span.findFirstVisibleItemPosition(StaggeredGridLayoutManager.java:2321)
//  at android.support.v7.widget.StaggeredGridLayoutManager.findFirstVisibleItemPositions(StaggeredGridLayoutManager.java:833)
//  at org.ligi.scr.MainActivity.onPause(MainActivity.java:165)
//  at android.app.Activity.performPause(Activity.java:6363)
//  at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1311)
//  at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3367)
//  ... 11 more
//
```

**Comment by ligi** [comment]
Sorry - overlooked this issue - just saw it now preparing this app for the 33C3 - cannot reproduce the issue unfortunately - can you reproduce the issue?
